// This file is part of the MultiReplace plugin for Notepad++.
// Copyright (C) 2023 Thomas Knoefel
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#include "MultiReplacePanel.h"


std::unordered_map<std::wstring, std::wstring> languageMap = {
{ L"panel_find_what", L"Find what: "},
{ L"panel_replace_with", L"Replace with: "},
{ L"panel_match_whole_word_only", L"Match whole word only" },
{ L"panel_match_case", L"Match case" },
{ L"panel_use_variables", L"Use Variables" },
{ L"panel_replace_at_matches", L"Replace matches:" },
{ L"panel_wrap_around", L"Wrap around" },
{ L"panel_search_mode", L"Search Mode" },
{ L"panel_normal", L"Normal" },
{ L"panel_extended", L"Extended (\\n, \\r, \\t, \\0, \\x...)" },
{ L"panel_regular_expression", L"Regular expression" },
{ L"panel_scope", L"Scope" },
{ L"panel_all_text", L"All Text" },
{ L"panel_selection", L"Selection" },
{ L"panel_csv", L"CSV" },
{ L"panel_cols", L"Cols:" },
{ L"panel_delim", L"Delim:" },
{ L"panel_quote", L"Quote:" },
{ L"panel_add_into_list", L"Add into List" },
{ L"panel_replace_all", L"Replace All" },
{ L"panel_replace", L"Replace" },
{ L"panel_find_next", L"Find Next" },
{ L"panel_find_next_small", L"Find Next"},
{ L"panel_mark_matches", L"Mark Matches" },
{ L"panel_mark_matches_small", L"Mark Matches"},
{ L"panel_clear_all_marks", L"Clear all marks" },
{ L"panel_load_list", L"Load List" },
{ L"panel_save_list", L"Save List" },
{ L"panel_save_as", L"Save As..." },
{ L"panel_export_to_bash", L"Export to Bash" },
{ L"panel_move_lines", L"Move Lines" },
{ L"panel_help", L"?" },
{ L"panel_replace_in_files",  L"Replace in Files" },
{ L"panel_directory", L"Directory: " },
{ L"panel_filter", L"Filter: " },
{ L"panel_in_subfolders", L"In all sub-folders" },
{ L"panel_in_hidden_folders", L"In hidden folders" },
{ L"panel_cancel_replace", L"Cancel Replace" },
{ L"panel_progress", L"Progress:" },

// File Dialog
{ L"filetype_all_files", L"All Files (*.*)" },
{ L"filetype_csv", L"CSV Files (*.csv)" },
{ L"filetype_bash", L"Bash Files (*.sh)" },

// Tooltips
{ L"tooltip_replace_all", L"Replace All" },
{ L"tooltip_2_buttons_mode", L"2 buttons mode" },
{ L"tooltip_columns", L"Columns: '1,3,5-12'" },
{ L"tooltip_delimiter", L"Delimiter: Single/combined chars, \\t for Tab" },
{ L"tooltip_quote", L"Quote: ', or \" or none" },
{ L"tooltip_replace_at_matches", L"Replace at matches (Replace All only): '1,3,5-12'" },
{ L"tooltip_sort_descending", L"Sort Descending" },
{ L"tooltip_sort_ascending", L"Sort Ascending" },
{ L"tooltip_drop_columns", L"Drop Columns" },
{ L"tooltip_copy_columns", L"Copy Columns to Clipboard" },
{ L"tooltip_column_highlight", L"Column highlight: On/Off" },
{ L"tooltip_copy_marked_text", L"Copy Marked Text" },
{ L"tooltip_display_statistics_columns", L"Show/Hide Statistics Columns" },
{ L"tooltip_new_list", L"New List" },
{ L"tooltip_save", L"Save List" },
{ L"tooltip_enable_list", L"Enable list" },
{ L"tooltip_disable_list", L"Disable list" },

// header entries
{ L"header_find_count", L"Find Count" },
{ L"header_replace_count", L"Replace Count" },
{ L"header_find", L"Find" },
{ L"header_replace", L"Replace" },
{ L"header_comments", L"Comments" },
{ L"header_delete_button", L"Delete Entry" },
{ L"header_whole_word", L"W" },
{ L"header_match_case", L"C" },
{ L"header_use_variables", L"V" },
{ L"header_extended", L"E" },
{ L"header_regex", L"R" },

// tooltip entries
{ L"tooltip_header_whole_word", L"Whole Word" },
{ L"tooltip_header_match_case", L"Match Case" },
{ L"tooltip_header_use_variables", L"Use Variables" },
{ L"tooltip_header_extended", L"Extended" },
{ L"tooltip_header_regex", L"Regex" },
{ L"tooltip_header_delete", L"Delete" },

// SplitButton entries
{ L"split_menu_replace_all", L"Replace All" },
{ L"split_menu_replace_all_in_docs", L"Replace All in All opened Documents" },
{ L"split_menu_replace_in_files", L"Replace in Files" },
{ L"split_button_replace_all", L"Replace All" },
{ L"split_button_replace_all_in_docs", L"Replace All in Docs" },
{ L"split_button_replace_in_files", L"Replace in Files" },

// Static Status message entries
{ L"status_duplicate_entry", L"Duplicate entry: " },
{ L"status_value_added", L"Value added to the list." },
{ L"status_no_rows_selected", L"No rows selected to shift." },
{ L"status_one_line_deleted", L"1 line deleted." },
{ L"status_column_marks_cleared", L"Column marks cleared." },
{ L"status_all_marks_cleared", L"All marks cleared." },
{ L"status_cannot_replace_read_only", L"Cannot replace. Document is read-only." },
{ L"status_add_values_instructions", L"Add values into the list. Or disable the list to replace directly." },
{ L"status_no_find_string", L"No 'Find String' entered. Please provide a value to add to the list." },
{ L"status_no_rows_selected_to_shift", L"No rows selected to shift." },
{ L"status_add_values_or_uncheck", L"Add values into the list or disable the list." },
{ L"status_no_occurrence_found", L"No occurrence found." },
{ L"status_found_text_not_replaced", L"Found text was not replaced." },
{ L"status_replace_one_next_found", L"Replace: 1 occurrence replaced. Next found." },
{ L"status_replace_one_none_left", L"Replace: 1 occurrence replaced. None left." },
{ L"status_replace_one", L"Replace: 1 occurrence replaced." },
{ L"status_add_values_or_find_directly", L"Add values into the list. Or disable the list to find directly." },
{ L"status_wrapped", L"Wrapped" },
{ L"status_no_matches_found", L"No matches found." },
{ L"status_no_matches_after_wrap", L"No matches found after wrap." },
{ L"status_add_values_or_mark_directly", L"Add values into the list. Or disable the list to mark directly." },
{ L"status_no_text_to_copy", L"No text to copy." },
{ L"status_failed_to_copy", L"Failed to copy to Clipboard." },
{ L"status_failed_allocate_memory", L"Failed to allocate memory for Clipboard." },
{ L"status_invalid_column_or_delimiter", L"Invalid column or delimiter data." },
{ L"status_missing_column_or_delimiter_data", L"Column data or delimiter data is missing" },
{ L"status_invalid_range_in_column_data", L"Invalid range in column data" },
{ L"status_missing_match_selection", L"Match selection data is missing" },
{ L"status_invalid_range_in_match_data", L"Invalid range in match selection" },
{ L"status_extended_delimiter_empty", L"Extended delimiter is empty" },
{ L"status_invalid_quote_character", L"Invalid quote character. Use \" or ' or leave it empty." },
{ L"status_unable_to_save_file", L"Error: Unable to open or write to file." },
{ L"status_saved_items_to_csv", L"$REPLACE_STRING items saved to CSV." },
{ L"status_no_valid_items_in_csv", L"No valid items found in the CSV file." },
{ L"status_list_exported_to_bash", L"List exported to BASH script." }, 
{ L"status_invalid_column_count", L"File not loaded! Invalid number of columns in CSV file." },
{ L"status_invalid_data_in_columns", L"File not loaded! Invalid data found in CSV columns." },
{ L"status_no_find_replace_list_input", L"No 'Find' or 'Replace' string provided. Please enter a value." },
{ L"status_found_in_list", L"Entry found in the list." },
{ L"status_not_found_in_list", L"No entry found in the list based on input fields." },
{ L"status_enable_list", L"List mode enabled. Actions will use list entries." },
{ L"status_disable_list", L"List mode disabled. Actions will use 'Find what' and 'Replace with' fields." },
{ L"status_new_list_created", L"New list created." },
{ L"status_no_rows_selected_to_delete", L"No rows selected to delete." },
{ L"status_invalid_indices", L"Invalid indices supplied." },
{ L"status_error_hidden_buffer", L"Error creating hidden buffer for processing." },
{ L"status_error_invalid_directory", L"The specified directory is invalid or does not exist." },
{ L"status_error_scanning_directory", L"Error scanning directory: $REPLACE_STRING" },

// Dynamic Status message entries
{ L"status_rows_shifted", L"$REPLACE_STRING rows successfully shifted." },
{ L"status_lines_deleted", L"$REPLACE_STRING lines deleted." },
{ L"status_occurrences_replaced", L"$REPLACE_STRING occurrences were replaced." },
{ L"status_no_matches_found_for", L"No matches found for '$REPLACE_STRING'." },
{ L"status_actual_position", L"Actual Position $REPLACE_STRING" },
{ L"status_items_loaded_from_csv", L"$REPLACE_STRING items loaded from CSV." },
{ L"status_occurrences_marked", L"$REPLACE_STRING occurrences were marked." },
{ L"status_items_copied_to_clipboard", L"$REPLACE_STRING items copied to Clipboard." },
{ L"status_no_matches_after_wrap_for", L"No matches found for '$REPLACE_STRING' after wrap." },
{ L"status_deleted_fields_count", L"Deleted $REPLACE_STRING fields." },
{ L"status_line_and_column_position", L" (Line: $REPLACE_STRING1, Column: $REPLACE_STRING2)" },
{ L"status_unable_to_open_file", L"Failed to open the file: $REPLACE_STRING" },

// MessageBox Titles
{ L"msgbox_title_error", L"Error" },
{ L"msgbox_title_confirm", L"Confirm" },
{ L"msgbox_title_use_variables_syntax_error", L"Use Variables: Syntax Error" },
{ L"msgbox_title_use_variables_execution_error", L"Use Variables: Execution Error" },
{ L"msgbox_title_save_list", L"Save list" },
{ L"msgbox_title_reload", L"Reload" },
{ L"msgbox_title_warning", L"Warning" },

// MessageBox Messages
{ L"msgbox_failed_create_control", L"Failed to create control with ID: $REPLACE_STRING1, GetLastError returned: $REPLACE_STRING2" },
{ L"msgbox_confirm_replace_all", L"Are you sure you want to replace all occurrences in all open documents?" },
{ L"msgbox_confirm_delete_columns", L"Are you sure you want to delete $REPLACE_STRING column(s)?" },
{ L"msgbox_error_saving_settings", L"An error occurred while saving the settings:<br/>$REPLACE_STRING" },
{ L"msgbox_use_variables_execution_error", L"Execution halted due to execution failure in:<br/>$REPLACE_STRING" },
{ L"msgbox_confirm_delete_single", L"Are you sure you want to delete this line?" },
{ L"msgbox_confirm_delete_multiple", L"Are you sure you want to delete $REPLACE_STRING lines?" },
{ L"msgbox_unsaved_changes_file", L"You have unsaved changes in the list: '$REPLACE_STRING'.<br/>Would you like to save them?" },
{ L"msgbox_unsaved_changes", L"You have unsaved changes.<br/>Would you like to save them?" },
{ L"msgbox_file_modified_prompt", L"'$REPLACE_STRING'<br/><br/>The file has been modified by another program.<br/>Do you want to load the changes and lose unsaved modifications?" },
{ L"msgbox_use_variables_not_exported", L"Some items with 'Use Variables' enabled were not exported." },
{ L"msgbox_no_files", L"No files matched the specified filter." },
{ L"msgbox_confirm_replace_in_files", L"Are you sure you want to perform replacement in $REPLACE_STRING file(s)?" },
{ L"msgbox_replace_done_in_files", L"Replacement finished.\n\n$REPLACE_STRING1 of $REPLACE_STRING2 file(s) were modified." },

// Context Menu Strings
{ L"ctxmenu_transfer_to_input_fields", L"&Transfer to Input Fields\tAlt+Up" },
{ L"ctxmenu_search_in_list", L"&Search in List\tCtrl+F" },
{ L"ctxmenu_cut", L"Cu&t\tCtrl+X" },
{ L"ctxmenu_copy", L"&Copy\tCtrl+C" },
{ L"ctxmenu_paste", L"&Paste\tCtrl+V" },
{ L"ctxmenu_edit", L"&Edit Field\t" },
{ L"ctxmenu_delete", L"&Delete\tDel" },
{ L"ctxmenu_select_all", L"Select &All\tCtrl+A" },
{ L"ctxmenu_enable", L"E&nable\tAlt+E" },
{ L"ctxmenu_disable", L"D&isable\tAlt+D" },
{ L"ctxmenu_undo", L"U&ndo\tCtrl+Z" },
{ L"ctxmenu_redo", L"R&edo\tCtrl+Y" },
{ L"ctxmenu_add_new_line", L"&Add New Line\tCtrl+I" }
};